/* Mission content is kept here so teachers can update it easily. */
const MISSIONS = [
  { title: "The Pirate’s Message", location: "Whiteboard", story: "Ahoy! A giant white surface at the front of the classroom is hiding our first clue.", puzzle: "I am big and white. Teachers write on me. What am I?", choices: ["Door", "Whiteboard", "Table", "Window"], answer: "Whiteboard", hint: "Look at the front of the classroom.", code: "428", point: [20.2, 29.4] },
  { title: "Boom Box Mystery", location: "TNT", story: "A mysterious boom box blocks the jungle path. Decode its name to travel safely!", puzzle: "Unscramble these letters: N · T · T", typedAnswer: true, answer: "TNT", hint: "It looks like something from a cartoon explosion.", code: "715", point: [42.5, 23.6] },
  { title: "The Missing Supplies", location: "Under the shoe box", story: "The ship’s supplies have vanished. Put Captain Wooby’s directions in the correct order.", puzzle: "the / Look / shoe box / under", choices: ["Look the shoe box under.", "Look under the shoe box.", "Under look the shoe box.", "The shoe box look under."], answer: "Look under the shoe box.", hint: "The first word is “Look.”", code: "263", point: [67.8, 25.8] },
  { title: "The Fresh Air Machine", location: "Air cleaner", story: "The cabin is foggy! Find the machine that keeps the crew’s air fresh.", puzzle: "I clean the air, but I am not a vacuum cleaner. What am I?", choices: ["Air cleaner", "Refrigerator", "Television", "Microwave"], answer: "Air cleaner", hint: "Find the machine that helps keep the room air fresh.", code: "891", point: [80.1, 43.9] },
  { title: "Golden Island", location: "Yellow tables", story: "Golden Island shines like sunshine. Find the classroom spot that matches its colour.", puzzle: "The sun and bananas are this colour. Find the tables with the same colour.", choices: ["Red tables", "Blue tables", "Yellow tables", "Black tables"], answer: "Yellow tables", hint: "It is a bright colour like the sun.", code: "546", point: [54.7, 61.1] },
  { title: "The Reflection Riddle", location: "Behind the mirror", story: "A silvery reflection guards the next clue. Complete the sentence to uncover it.", puzzle: "I can see myself in a ________. Then look behind it!", choices: ["book", "mirror", "chair", "bag"], answer: "mirror", hint: "You use it to see your face.", code: "203", point: [31.6, 70.5] },
  { title: "The Captain’s Seat", location: "Second black chair", story: "Every captain needs a special seat. Count carefully before choosing yours.", puzzle: "Find the black chairs. Count from left to right. Look at chair number two.", choices: ["First black chair", "Second black chair", "Third black chair", "Yellow chair"], answer: "Second black chair", hint: "One, TWO, three.", code: "674", point: [12.8, 55.8] },
  { title: "The Hidden Treasure", location: "Final on-screen treasure", story: "The treasure is close! Read the first letter of every word to reveal the secret.", puzzle: "Tiger · Rabbit · Elephant · Apple · Sun · Umbrella · Robot · Egg", choices: ["ADVENTURE", "DINOSAUR", "TREASURE", "WONDERLAND"], answer: "TREASURE", hint: "Read the big first letter of every word.", final: true, point: [71.2, 76.2] }
];
